services:
#    parametre.example:
#        class: ParametreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    parametre.service:
        class: DalBundle\Services\ParametreService
        arguments: ["%doctrine.default_entity_manager%"]